### ISSUE TITLE
Problems installing app runtime

### ISSUE THREAD

**Issue by mrcwatling** [nkasco/IT-Admin-Toolkit-WinUI#29]
Hi,

We have been having a lot of issues getting the app runtime working on our PC's to run this toolkit and wondering if you can point us in the right direction.

When setting up on a new machine we get the prompt to install the Windows App Runtime, we download 1.1 version installer and install but when launching the application we still get prompted to install the Windows App Runtime.

![image](https://user-images.githubusercontent.com/13342630/211234501-3acd988a-5bfb-41b9-bb01-2e9e6a11cf7e.png)

![image](https://user-images.githubusercontent.com/13342630/211234525-16097307-d00b-446c-a4f8-e0c262186cf3.png)

Just now sure where to go next, do we have the wrong version installed or is there another issue?

**Comment by nkasco** [comment]
Hmm have you given the latest a try?
[https://aka.ms/windowsappsdk/1.2/1.2.221209.1/Microsoft.WindowsAppRuntime.Redist.1.2.zip](https://aka.ms/windowsappsdk/1.2/1.2.221209.1/Microsoft.WindowsAppRuntime.Redist.1.2.zip)

Make sure you are installing specifically the redistributable.

**Comment by mrcwatling** [comment]
HI,

I installed the one you suggested above, but when trying to launch the program it's still saying that it is not installed and that I need to install a compatible Windows App Runtime. 

Any other suggestions?

**Comment by nkasco** [comment]
I will spin up a fresh VM with nothing pre-loaded and report back. I had done that prior so I'm confused why you're still getting that error after installing the runtime.

**Comment by nkasco** [comment]
I was able to repro your issue with a fresh VM, I'm not quite sure why 1.2.x isn't backward compatible with 1.1.x. That said, to resolve you'd have to use this workaround:

- Since the -f switch doesn't work to force 1.1.5 to install on top of 1.2, you must remove all installed versions of the Windows App SDK redistributable and reinstall in order:
    - Launch Windows PowerShell as admin and run: `Get-AppxPackage micro*win*appruntime* -AllUsers | Remove-AppxPackage -AllUsers`
    - Download the [1.1.5 redistributable](https://aka.ms/windowsappsdk/1.1/1.1.5/Microsoft.WindowsAppRuntime.Redist.1.1.5.zip) and install WindowsAppRuntimeInstall.exe as admin from the WindowsAppSDK-Installer-x64 folder
    - Download the [1.2.2 redistributable](https://aka.ms/windowsappsdk/1.2/1.2.221209.1/Microsoft.WindowsAppRuntime.Redist.1.2.zip) and install WindowsAppRuntimeInstall.exe as admin from the WindowsAppSDK-Installer-x64 folder

Only 1.1.5 is required for the app to run right now, I will be looking into ways to better control this in the future but I think it's really just a Microsoft bug to be honest. Hope this helps!

**Comment by nkasco** [comment]
This should be avoided for now as I just bumped up the Windows App SDK version to 1.2.221209.1 with #30, there is no release yet so you'd have to build it yourself. There will be a number of updates coming soon that will lead to a release.

**Comment by mrcwatling** [comment]
Thanks for the help and the writing this program, I'll have a look and see if I can compile the project, I haven't done anything like that before so any clues? Also any clues as to when the next release will be (are we talking months or sooner)?

**Comment by nkasco** [comment]
I went ahead and added a v1.0.7 pre-release:
https://github.com/nkasco/IT-Admin-Toolkit-WinUI/releases/tag/v1.0.7

Please be aware of #34 as you will have to manually mitigate for now.

If you have auto-update turned on it should detect it, #35 will improve that UX eventually. You may want to just start fresh though for simplicity and some of the UI defaults I think are better than the configuration that would otherwise be preserved by updating.
