### ISSUE TITLE
Application could not be started

### ISSUE THREAD

**Issue by lunatik98** [nkasco/IT-Admin-Toolkit-WinUI#44]
When I try to start the programm I get this error message:

![2023-03-04 22_31_34-Window](https://user-images.githubusercontent.com/83845172/222929673-33c3c3ab-67b3-4b5e-9663-abe8591a3663.png)

I installed the Windows App SDK 1.2 from the website and rebooted. Is there another requirement or is this the wrong version?

I use Windows Server 2019.

**Comment by nkasco** [comment]
Might be similar to #29, try a similar workaround from there and see how it goes.

**Comment by lunatik98** [comment]
I tried to install the older version and then the newer version but I still get the same message :(

![2023-03-04 23_17_09-Window](https://user-images.githubusercontent.com/83845172/222931106-645f04ad-14c1-43f7-9d97-f4f469300ffb.png)

**Comment by nkasco** [comment]
I went and grabbed a Windows Server 2019 iso and was able to get it working...

Looks like you may need to enable sideloading because the DDLM component fails to install by default
![image](https://user-images.githubusercontent.com/1930697/222932357-369246dd-19cc-4f0c-a4f0-c3079a087366.png)

Try this first, then if necessary install the redist from the zip link below:
- Settings
- Search "Developer settings"
- Enable "Developer mode"
- If necessary, you can try https://aka.ms/windowsappsdk/1.2/1.2.221209.1/Microsoft.WindowsAppRuntime.Redist.1.2.zip 

![image](https://user-images.githubusercontent.com/1930697/222932380-3e2dde4e-a4e4-4c0c-904c-62b32c5f1c2f.png)

Then I was able to run without issue:
![image](https://user-images.githubusercontent.com/1930697/222932464-635a18d6-9d9c-4c89-83c9-f25aadaf4b32.png)

**Comment by Joeya1ds** [comment]
While testing this tool I ran into the exact same issue.
Adding this line under propertygroup: "WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained" to the .csproj file resolved the issue for me.

**Comment by Mattw11486** [comment]
> While testing this tool I ran into the exact same issue. Adding this line under propertygroup: "WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained" to the .csproj file resolved the issue for me.

Thank you this is the answer!
